language: go

go:
  - '1.11'

services:
  - docker
  
branches:
  only:
  - master

env:
  - GO111MODULE=on

script:
  - go test -coverprofile=coverage.txt ./nproto/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
